import { CaseStudy, Testimonial, Mentorship } from './api';

export const mockCaseStudies: CaseStudy[] = [
  {
    _id: '1',
    title: 'Vodafone Planner Tool',
    slug: 'vodafone-planner-tool',
    coverImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&h=800&fit=crop',
    caseStudyImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1600&h=900&fit=crop',
    problemStatement: 'Led the development of a ticket dispatching tool using the design thinking framework to uncover the underlying issues affecting the company\'s finances due to duplicate tickets. The challenge was to streamline workflows across three different user personas while maintaining operational efficiency.',
    myRole: 'Lead Product Designer - Conducted user research, created wireframes and prototypes, led usability testing sessions, and collaborated with development teams to implement the solution.',
    keyMetrics: [
      {
        metric: 'Duplicate Tickets Reduced',
        value: '95%',
        description: 'Achieved a 95% reduction in duplicate tickets through optimized workflows and smart automation',
      },
      {
        metric: 'User Satisfaction',
        value: '92%',
        description: 'User satisfaction increased significantly with the new streamlined interface',
      },
      {
        metric: 'Time Saved',
        value: '40hrs/week',
        description: 'Teams save an average of 40 hours per week with automated processes',
      },
    ],
    prototypeLink: 'https://www.figma.com/proto/example',
    videoLink: 'https://www.youtube.com/watch?v=example',
    tags: ['UX Research', 'Design Thinking', 'Enterprise', 'Vodafone'],
    isFeatured: true,
    createdAt: '2024-01-15',
  },
  {
    _id: '2',
    title: 'Workforce Management Platform',
    slug: 'workforce-management-platform',
    coverImage: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1200&h=800&fit=crop',
    caseStudyImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1600&h=900&fit=crop',
    problemStatement: 'Transforming Vodafone\'s operations through the creation of a resource management platform. The overwhelming number of resources were difficult to oversee, and project managers often resorted to external hiring even when internal candidates were available.',
    myRole: 'Senior Product Designer - End-to-end design ownership including user research, information architecture, UI design, and stakeholder management across multiple markets.',
    keyMetrics: [
      {
        metric: 'Bench Resources Reduced',
        value: '80%',
        description: 'Reduced bench resources by 80% during the first rollout by optimizing resource allocation',
      },
      {
        metric: 'External Hiring Decreased',
        value: '60%',
        description: 'External hiring decreased by 60% during the initial release phase',
      },
      {
        metric: 'Resource Utilization',
        value: '94%',
        description: 'Improved overall resource utilization to 94% across all departments',
      },
    ],
    prototypeLink: 'https://www.figma.com/proto/example2',
    tags: ['Resource Management', 'Enterprise', 'SaaS', 'Vodafone'],
    isFeatured: true,
    createdAt: '2024-02-20',
  },
  {
    _id: '3',
    title: 'VOIS Global Hackathon Platform',
    slug: 'vois-global-hackathon',
    coverImage: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&h=800&fit=crop',
    caseStudyImage: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1600&h=900&fit=crop',
    problemStatement: 'Led design efforts for an annual 3D Virtual Hackathon. Created a comprehensive digital ecosystem with a landing page, registration flow, judges panel interface, and more to engage teams across multiple countries.',
    myRole: 'Lead UX/UI Designer - Designed the complete virtual experience including 3D environments, user flows, and interactive elements for a global event.',
    keyMetrics: [
      {
        metric: 'Teams Engaged',
        value: '450+',
        description: 'Successfully engaged over 450 teams from Egypt, Romania, and India',
      },
      {
        metric: 'User Satisfaction',
        value: '96%',
        description: 'Participants rated the platform experience 96% positive',
      },
      {
        metric: 'Completion Rate',
        value: '89%',
        description: '89% of registered teams completed the full hackathon journey',
      },
    ],
    tags: ['3D Design', 'Event Platform', 'Virtual Events', 'Vodafone'],
    isFeatured: true,
    createdAt: '2023-11-10',
  },
  {
    _id: '4',
    title: 'Idea Management Tool',
    slug: 'idea-management-tool',
    coverImage: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=1200&h=800&fit=crop',
    caseStudyImage: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=1600&h=900&fit=crop',
    problemStatement: 'Created an automated platform for managing stakeholder tools within the company. Previously, stakeholders faced an unclear process for handling new tools, leading to inefficiency and low satisfaction.',
    myRole: 'Product Designer - Designed the complete user experience from ideation submission to approval workflows, ensuring stakeholder needs were met.',
    keyMetrics: [
      {
        metric: 'Efficiency Increased',
        value: '90%',
        description: 'Improved efficiency to 90% with the new automated approach',
      },
      {
        metric: 'Stakeholder Satisfaction',
        value: '88%',
        description: 'Stakeholder satisfaction soared to 88% compared to just 30% with traditional method',
      },
      {
        metric: 'Processing Time',
        value: '75%',
        description: 'Reduced idea processing time by 75% through automation',
      },
    ],
    tags: ['Process Automation', 'Enterprise', 'Internal Tools', 'Vodafone'],
    isFeatured: false,
    createdAt: '2023-09-05',
  },
  {
    _id: '5',
    title: 'VOIS Markets AR Application',
    slug: 'vois-markets-ar-app',
    coverImage: 'https://images.unsplash.com/photo-1617802690992-15d93263d3a9?w=1200&h=800&fit=crop',
    caseStudyImage: 'https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?w=1600&h=900&fit=crop',
    problemStatement: 'Spearheaded the design of an augmented reality 3D application that highlights all VOIS markets. This initiative aimed to strengthen remote work connections and foster relationships across various VOIS markets through immersive technology.',
    myRole: 'AR/VR Designer - Comprehensive user research, 3D interface design, and interaction design for an innovative AR experience.',
    keyMetrics: [
      {
        metric: 'User Engagement',
        value: '85%',
        description: 'Daily active user engagement rate of 85% across all markets',
      },
      {
        metric: 'Connection Quality',
        value: '78%',
        description: 'Users reported 78% improvement in cross-market connections',
      },
    ],
    tags: ['AR/VR', '3D Design', 'Innovation', 'Vodafone'],
    isFeatured: false,
    createdAt: '2023-07-22',
  },
  {
    _id: '6',
    title: 'Money Fellows LMS',
    slug: 'money-fellows-lms',
    coverImage: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&h=800&fit=crop',
    caseStudyImage: 'https://images.unsplash.com/photo-1513258496099-48168024aec0?w=1600&h=900&fit=crop',
    problemStatement: 'Conducted user research and designed the UI for a Learning Management System within the financial sector to enhance user skills and knowledge.',
    myRole: 'UX/UI Designer - User research, interface design, and usability testing for financial education platform.',
    keyMetrics: [
      {
        metric: 'Course Completion',
        value: '87%',
        description: 'High course completion rate of 87% due to intuitive design',
      },
      {
        metric: 'Learning Efficiency',
        value: '45%',
        description: 'Users learn 45% faster with the new interface',
      },
    ],
    tags: ['FinTech', 'LMS', 'Education', 'Finance'],
    isFeatured: false,
    createdAt: '2023-05-18',
  },
];

export const mockTestimonials: Testimonial[] = [
  {
    _id: 't1',
    quote: 'Amgad\'s design thinking approach transformed our entire workflow. The Planner Tool he designed saved us countless hours and significantly reduced operational costs. His attention to detail and user-centric design philosophy is exceptional.',
    authorName: 'Sarah Mitchell',
    authorTitle: 'Senior Product Manager',
    clientCompany: 'Vodafone Italy',
    authorImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
    authorLinkedIn: 'https://linkedin.com/in/example',
    rating: 5,
    projectName: 'Vodafone Planner Tool',
    testimonialType: 'Client',
    isFeatured: true,
    createdAt: '2024-01-20',
  },
  {
    _id: 't2',
    quote: 'Working with Amgad at VOIS was an incredible experience. His ability to translate complex business requirements into intuitive user interfaces is remarkable. The Workforce Management Platform exceeded all our expectations.',
    authorName: 'James Anderson',
    authorTitle: 'Director of Operations',
    clientCompany: 'Vodafone UK',
    authorImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop',
    rating: 5,
    projectName: 'Workforce Management',
    testimonialType: 'Client',
    isFeatured: true,
    createdAt: '2024-02-15',
  },
  {
    _id: 't3',
    quote: 'As Amgad\'s mentee at ITI, I learned not just design skills but how to think like a product designer. His teaching style is engaging, practical, and industry-focused. I landed my first design job within weeks of completing his course!',
    authorName: 'Maya Hassan',
    authorTitle: 'Junior UX Designer',
    clientCompany: 'StartupHub Cairo',
    authorImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
    rating: 5,
    testimonialType: 'Student',
    isFeatured: true,
    createdAt: '2023-12-10',
  },
  {
    _id: 't4',
    quote: 'Amgad brings a unique blend of technical knowledge and creative vision to every project. His engineering background gives him an edge in understanding complex systems while his design expertise ensures beautiful, functional solutions.',
    authorName: 'David Chen',
    authorTitle: 'Lead Developer',
    clientCompany: 'Vodafone Germany',
    authorImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop',
    rating: 5,
    testimonialType: 'Colleague',
    isFeatured: false,
    createdAt: '2023-11-25',
  },
  {
    _id: 't5',
    quote: 'The mentorship sessions with Amgad were game-changing. He helped me understand UX research methodologies, portfolio building, and how to approach design challenges systematically. Highly recommend!',
    authorName: 'Omar Khalil',
    authorTitle: 'Aspiring Product Designer',
    authorImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
    rating: 5,
    testimonialType: 'Mentee',
    isFeatured: false,
    createdAt: '2023-10-30',
  },
  {
    _id: 't6',
    quote: 'Amgad\'s work on our AR application was phenomenal. He understood the cutting-edge technology and created an experience that was both innovative and user-friendly. A true tech-forward designer.',
    authorName: 'Lisa Rodriguez',
    authorTitle: 'Innovation Lead',
    clientCompany: 'VOIS Egypt',
    authorImage: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200&h=200&fit=crop',
    rating: 5,
    projectName: 'AR Markets App',
    testimonialType: 'Client',
    isFeatured: false,
    createdAt: '2023-09-15',
  },
];

export const mockMentorshipSessions: Mentorship[] = [
  {
    _id: 'm1',
    title: 'UX Portfolio Review & Career Guidance',
    slug: 'ux-portfolio-review',
    sessionType: 'one-on-one',
    targetAudience: 'Aspiring & Junior Designers',
    description: 'Get expert feedback on your UX/UI portfolio and receive personalized career guidance. I\'ll help you identify strengths, address gaps, and create a portfolio that stands out to hiring managers.',
    whatToExpect: [
      'Comprehensive portfolio review with detailed feedback',
      'Industry insights and hiring trends discussion',
      'Tips for presenting your work effectively',
      'Career roadmap and next steps planning',
      'Q&A session tailored to your goals',
    ],
    preparationRequired: 'Please share your portfolio link or PDF at least 24 hours before the session.',
    duration: '90 minutes',
    price: 150,
    offerPrice: 99,
    offerEndDate: '2025-12-31',
    currency: 'USD',
    bookingLink: 'https://calendly.com/amgadhassan/portfolio-review',
    testimonials: [
      {
        author: 'Maya Hassan',
        quote: 'The portfolio review session was incredibly valuable. Amgad provided actionable feedback that helped me land three interviews!',
      },
    ],
    isActive: true,
    isFeatured: true,
    createdAt: '2024-01-01',
  },
  {
    _id: 'm2',
    title: 'Design Thinking Workshop',
    slug: 'design-thinking-workshop',
    sessionType: 'workshop',
    targetAudience: 'All Levels',
    description: 'Learn the complete design thinking process through hands-on exercises. We\'ll work through real-world problems using the same frameworks I use at Vodafone to launch successful products.',
    whatToExpect: [
      'Introduction to design thinking methodology',
      'Hands-on problem-solving exercises',
      'User research techniques and tools',
      'Ideation and prototyping strategies',
      'Case study walkthrough from actual projects',
      'Actionable templates and resources',
    ],
    preparationRequired: 'Come with a product or feature idea you\'d like to explore during the workshop.',
    duration: '120 minutes',
    price: 200,
    currency: 'USD',
    bookingLink: 'https://calendly.com/amgadhassan/design-thinking',
    testimonials: [
      {
        author: 'Omar Khalil',
        quote: 'This workshop completely changed how I approach design problems. The frameworks are immediately applicable!',
      },
    ],
    isActive: true,
    isFeatured: true,
    createdAt: '2024-01-05',
  },
  {
    _id: 'm3',
    title: 'From Figma to Development: Handoff Mastery',
    slug: 'figma-developer-handoff',
    sessionType: 'course',
    targetAudience: 'Intermediate Designers',
    description: 'Master the art of design handoff and collaboration with developers. Learn how to create design systems, component libraries, and documentation that developers love.',
    whatToExpect: [
      'Best practices for design system creation',
      'Component documentation techniques',
      'Developer-friendly naming conventions',
      'Auto-layout and responsive design in Figma',
      'Effective communication with development teams',
    ],
    preparationRequired: 'Basic Figma knowledge required. Please bring a current project to work on.',
    duration: '90 minutes',
    price: 175,
    offerPrice: 125,
    offerEndDate: '2025-11-30',
    currency: 'USD',
    bookingLink: 'https://calendly.com/amgadhassan/figma-handoff',
    isActive: true,
    isFeatured: true,
    createdAt: '2024-01-10',
  },
  {
    _id: 'm4',
    title: 'UX Research Fundamentals',
    slug: 'ux-research-fundamentals',
    sessionType: 'course',
    targetAudience: 'Beginners & Career Switchers',
    description: 'Dive into UX research methodologies and learn how to gather insights that drive design decisions. Perfect for those new to user research or looking to strengthen their research skills.',
    whatToExpect: [
      'Overview of qualitative and quantitative research methods',
      'How to plan and conduct user interviews',
      'Survey design best practices',
      'Usability testing fundamentals',
      'Synthesizing research into actionable insights',
    ],
    duration: '60 minutes',
    price: 100,
    currency: 'USD',
    bookingLink: 'https://calendly.com/amgadhassan/ux-research',
    isActive: true,
    isFeatured: false,
    createdAt: '2024-01-15',
  },
  {
    _id: 'm5',
    title: '1-on-1 Career Coaching',
    slug: 'career-coaching',
    sessionType: 'one-on-one',
    targetAudience: 'All Levels',
    description: 'Personalized career coaching session to help you navigate your UX/UI design career. Whether you\'re looking to break into the field, advance to senior roles, or transition to product design.',
    whatToExpect: [
      'Career assessment and goal setting',
      'Industry insights from 4+ years at Vodafone',
      'Salary negotiation strategies',
      'Building your personal brand',
      'Networking and job search tactics',
    ],
    duration: '60 minutes',
    price: 125,
    currency: 'USD',
    bookingLink: 'https://calendly.com/amgadhassan/career-coaching',
    isActive: true,
    isFeatured: false,
    createdAt: '2024-01-20',
  },
];
